<?php
/**
 * PlansPlanPermissionTest
 *
 * PHP version 8.1
 *
 * @package  Equisoft\SDK\EquisoftPlan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /plan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-equisoft1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Equisoft\SDK\EquisoftPlan\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PlansPlanPermissionTest Class Doc Comment
 *
 * @description The permission of a user on a plan
 * @package     Equisoft\SDK\EquisoftPlan
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PlansPlanPermissionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PlansPlanPermission"
     */
    public function testPlansPlanPermission()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "userUuid"
     */
    public function testPropertyUserUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "permission"
     */
    public function testPropertyPermission()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
