<?php
/**
 * CmdCopyFNATest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftPlan
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /plan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-equisoft2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Equisoft\SDK\EquisoftPlan\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CmdCopyFNATest Class Doc Comment
 *
 * @category    Class
 * @description CmdCopyFNA
 * @package     Equisoft\SDK\EquisoftPlan
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CmdCopyFNATest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CmdCopyFNA"
     */
    public function testCmdCopyFNA()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fnaUuid"
     */
    public function testPropertyFnaUuid()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "userEmail"
     */
    public function testPropertyUserEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "newParticipantUuids"
     */
    public function testPropertyNewParticipantUuids()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
